import Foundation

public enum MacEnvError: Error, LocalizedError, Equatable {
    case invalidVariableName(String)
    case originalContentChanged(String)

    public var errorDescription: String? {
        switch self {
        case .invalidVariableName(let name):
            "Invalid shell variable name: \(name)"
        case .originalContentChanged(let path):
            "File changed before apply: \(path)"
        }
    }
}

public struct ChangePlanner {
    public var homeDirectory: URL
    public var fileManager: FileManager

    public init(homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser, fileManager: FileManager = .default) {
        self.homeDirectory = homeDirectory
        self.fileManager = fileManager
    }

    public func plan(snapshot: EnvironmentSnapshot) throws -> ChangeSet {
        try validate(snapshot: snapshot)

        let managedURL = homeDirectory.appendingPathComponent(ShellFileScanner.managedRelativePath)
        let managedPath = managedURL.path
        let managedOriginal = readIfExists(managedURL)
        let managedBlock = ShellGenerator().managedBlock(
            variables: snapshot.variables.filter { $0.source == .managed || $0.isTakenOver },
            pathEntries: snapshot.pathEntries
        )
        let managedUpdated = replacingManagedBlock(in: managedOriginal, with: managedBlock)

        var changes = [
            FileChange(
                path: managedPath,
                original: managedOriginal,
                updated: managedUpdated,
                diff: DiffBuilder.diff(path: managedPath, original: managedOriginal, updated: managedUpdated)
            )
        ]

        for source in snapshot.sources where source.isEnabled && source.path != managedPath {
            let original = readIfExists(URL(fileURLWithPath: source.path))
            let block = sourceBlock(forManagedPath: managedPath)
            var updated = replacingManagedBlock(in: original, with: block)
            updated = markingTakenOverDefinitions(in: updated, sourcePath: source.path, variables: snapshot.variables)
            changes.append(
                FileChange(
                    path: source.path,
                    original: original,
                    updated: updated,
                    diff: DiffBuilder.diff(path: source.path, original: original, updated: updated)
                )
            )
        }

        let sourceCommands = Array(NSOrderedSet(array: snapshot.sources
            .filter { $0.isEnabled }
            .map { "source \($0.path)" }
        )) as? [String] ?? []

        return ChangeSet(changes: changes, warnings: warnings(for: snapshot), sourceCommands: sourceCommands)
    }

    private func validate(snapshot: EnvironmentSnapshot) throws {
        for variable in snapshot.variables where !ShellSyntax.isValidVariableName(variable.name) {
            throw MacEnvError.invalidVariableName(variable.name)
        }
    }

    private func warnings(for snapshot: EnvironmentSnapshot) -> [String] {
        var warnings: [String] = []
        for entry in snapshot.pathEntries where entry.isDuplicate {
            warnings.append("Duplicate PATH entry: \(entry.value)")
        }
        for variable in snapshot.variables where isLikelySecret(variable.name) {
            warnings.append("Sensitive-looking variable is shown in plaintext: \(variable.name)")
        }
        return warnings
    }

    private func readIfExists(_ url: URL) -> String {
        guard fileManager.fileExists(atPath: url.path) else { return "" }
        return (try? String(contentsOf: url, encoding: .utf8)) ?? ""
    }

    private func replacingManagedBlock(in content: String, with block: String) -> String {
        guard
            let begin = content.range(of: ShellSyntax.beginMarker),
            let end = content.range(of: ShellSyntax.endMarker, range: begin.upperBound..<content.endIndex)
        else {
            if content.isEmpty {
                return block
            }
            return content.hasSuffix("\n") ? content + block : content + "\n" + block
        }

        let replacementRange = begin.lowerBound..<end.upperBound
        var updated = content
        updated.replaceSubrange(replacementRange, with: block.trimmingCharacters(in: .newlines))
        if !updated.hasSuffix("\n") {
            updated.append("\n")
        }
        return updated
    }

    private func sourceBlock(forManagedPath managedPath: String) -> String {
        [
            ShellSyntax.beginMarker,
            "# Generated by Mac Env Manager. Keep this block so shell sessions load managed variables.",
            "source \(ShellSyntax.shellSingleQuote(managedPath))",
            ShellSyntax.endMarker
        ].joined(separator: "\n") + "\n"
    }

    private func markingTakenOverDefinitions(in content: String, sourcePath: String, variables: [EnvVariable]) -> String {
        let takenOverNames = Set(variables.compactMap { variable -> String? in
            guard variable.isTakenOver else { return nil }
            guard case .dotfile(let path) = variable.source, path == sourcePath else { return nil }
            return variable.name
        })
        guard !takenOverNames.isEmpty else { return content }

        return content.components(separatedBy: .newlines).map { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            for name in takenOverNames {
                if trimmed.hasPrefix("export \(name)=") || trimmed.hasPrefix("\(name)=") {
                    return "# Mac Env Manager takeover: \(line)"
                }
            }
            return line
        }.joined(separator: "\n")
    }

    private func isLikelySecret(_ name: String) -> Bool {
        let uppercased = name.uppercased()
        return ["KEY", "TOKEN", "SECRET", "PASSWORD"].contains { uppercased.contains($0) }
    }
}

public enum DiffBuilder {
    public static func diff(path: String, original: String, updated: String) -> String {
        guard original != updated else { return "" }
        var lines = ["--- \(path)", "+++ \(path)"]
        let originalLines = original.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        let updatedLines = updated.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        for line in originalLines where !line.isEmpty {
            lines.append("- \(line)")
        }
        for line in updatedLines where !line.isEmpty {
            lines.append("+ \(line)")
        }
        return lines.joined(separator: "\n")
    }
}
