import Foundation

public struct ShellGenerator: Sendable {
    public init() {}

    public func managedBlock(variables: [EnvVariable], pathEntries: [PathEntry]) -> String {
        var lines = [
            ShellSyntax.beginMarker,
            "# Generated by Mac Env Manager. Edit through the app when possible."
        ]

        for variable in variables {
            guard ShellSyntax.isValidVariableName(variable.name) else { continue }
            let assignment = "\(variable.isExported ? "export " : "")\(variable.name)=\(ShellSyntax.shellSingleQuote(variable.value))"
            if variable.isEnabled {
                lines.append(assignment)
            } else {
                lines.append("# \(assignment) \(ShellSyntax.disabledMarker)")
            }
        }

        appendPathLines(from: pathEntries, to: &lines)
        lines.append(ShellSyntax.endMarker)
        return lines.joined(separator: "\n") + "\n"
    }

    private func appendPathLines(from pathEntries: [PathEntry], to lines: inout [String]) {
        var seen: Set<String> = []
        let enabledEntries = pathEntries.compactMap { entry -> String? in
            guard entry.isEnabled else { return nil }
            guard !seen.contains(entry.value) else { return nil }
            seen.insert(entry.value)
            return entry.value
        }

        if !enabledEntries.isEmpty {
            lines.append("export PATH=\(ShellSyntax.shellSingleQuote(enabledEntries.joined(separator: ":"))):$PATH")
        }

        for entry in pathEntries where !entry.isEnabled {
            lines.append("# PATH entry disabled: \(entry.value)")
        }
    }
}
